#'Finds the local maxima for a list of fitted experiments
#'
#'Given a list of lists of spectra (i.e. each item of the list is a list of spectra as generated by \code{\link[psRIIfit]{spect.frametolist}}) and a table of peak parameters, finds the true maxima within the peaks' ranges.
#'@param bigList A list containing lists of data frames of spectra with columns "absorbance" and "wavelength"
#'@param posTable A data frame or matrix containing the centres and widths of peaks. Columns should alternate as the centre and width of a peak, with the centre first.
#'@export

findAllPeaks <- function(bigList, posTable){
  peakNo <- ncol(posTable)/2
  peakList <- list()
  for(i in 1:length(bigList)){
    centreVec <- c()
    widthVec <- c()
    for(j in 1:peakNo){
      centreVec[j] <- posTable[i, (2*j) - 1]
      widthVec[j] <- posTable[i, 2*j]
    }
    peakList[[i]] <- realPeakFinder(spectraList = bigList[[i]], centres = centreVec, widths = widthVec)
    peakList[[i]]
  }
  names(peakList) <-names(bigList)
  peakList
}
